### ISSUE TITLE
f008 bottom fan randomly started on its on

### ISSUE THREAD

**Issue by j6kim** [SoftwareDefinedBuildings/PECS-chair#5] opened 2015-07-23 22:18 UTC
1) chair id: f008 in Therese's office
2) problem: the chair was off the whole time. but the bottom fan randomly started on its on several times
3) trouble shooting: unplugged & replugged the power. so fat it seems to be okay...

**Comment by gtfierro** [comment] 2015-07-23 22:38
This could be a side effect of some other experiments being done. I don't think this is an actual issue w/ the chair. @immesys could you have actuated this by accident?

**Comment by immesys** [comment] 2015-07-24 04:53
No. I only ever actuated f006 and f00d. Sam does have code to "resume" settings so it is possible for the chair firmware to have deviced to change itself.

**Comment by j6kim** [comment] 2015-07-24 07:44
One more information - before the bottom fan randomly started on its on, I switched her phone from Airbears2 to CalVisitor to show her the pop-up msgs that she would get if the chair data can't be pushed to sMap. After a few minutes, I switched back to Airbears2. That's when the bottom fan randomly started on its on. The chair setting was off before I switched the wireless network on her phone.

**Comment by OpenBASGuest** [comment] 2015-07-24 16:37
This morning when I sat down, the bottom fan turned on. I tried to turn it off with the phone but the message was that it was waiting for bluetooth. I unplugged what I think is the power cord (coax pin type), replugged, and all is fine now. The temperature on the tstat on the wall reads 75F because the morning sun is streaming in. Not sure that's related....

**Comment by gtfierro** [comment] 2015-07-24 16:44
@immesys there might be some merit to going through the code and ripping out all of Sam's old resume stuff. What would **really** be nice is being able to download the logs off of a phone and chair so we could replay what happened.

@OpenBASGuest let us know if this happens again. Did you have the fans on previously (like yesterday?)

**Comment by samkumar** [comment] 2015-07-24 16:47
I'm fairly sure that the resume code isn't on master any more. I'll double-check tonight.

-Sam

**Comment by gtfierro** [comment] 2015-07-24 16:48
Cool, thanks. There's also a small chance there's an edge case in the remote actuation code, but the logic is pretty straightforward for that and I can't think of what the problem would be unless an app or chair lies about its ID.

**Comment by samkumar** [comment] 2015-07-24 16:49
I also want to mention that a wrote a program to read the chair logs and print them out. But I have not tested it in a few months, and meanwhile the way in which the chair logs data has changed substantially. I will take a look at it and update it as needed and let you know when it's ready.

-Sam

**Comment by gtfierro** [comment] 2015-07-24 16:50
I mean the logs of what happens on the chair, including but beyond just the state of the fans/heaters/etc

**Comment by samkumar** [comment] 2015-07-24 16:51
When the chair fans turned on, did the phone show the fan as being on? Or was the phone still showing the neutral setting?

-Sam

**Comment by shankari** [comment] 2015-07-24 17:05
@gtfierro @immesys @samkumar99 I also ran into issues with not having long-term access to logs on the phone - `adb logcat` typically shows you only a few hours worth of information. So I spent the time to write up and test a single java class solution for logging to files that you can then retrieve from the phone using `adb pull`. Should be trivial to add support for uploading using a REST API if you don't want to hook up the phone - if you do end up doing that, I'll use it too :)

https://github.com/e-mission/e-mission-data-collection/blob/master/android/app/src/main/java/edu/berkeley/eecs/cfc_tracker/log/Log.java

On a general note, if you are doing phone work, you might want to subscribe to https://github.com/e-mission/e-mission-phone and/or https://github.com/e-mission/e-mission-data-collection to see what I'm working on, and whether there's any code that you can reuse.

**Comment by j6kim** [comment] 2015-07-24 17:47
For Therese's chair, the phone showed the fan being on when it started on its own.

**Comment by gtfierro** [comment] 2015-07-24 17:57
@j6kim Isn't that expected behavior then?

**Comment by j6kim** [comment] 2015-07-24 18:07
But she didn't change the phone setting. It automatically switched from off to on.

**Comment by OpenBASGuest** [comment] 2015-07-24 18:32
@gtfierro  @samkumar99 As Joyce says, I did not use the phone app to turn on the bottom fan, it just turned on by itself several times yesterday and first thing this morning. The phone app did tend to show that the bottom fan was in fact on, and I was able to use the app to turn it off. yesterday I thought that it was somehow related to Joyce and my voices (certainly we were talking about the chair, fans, cooling etc), but this morning I hadn't said a word....

**Comment by immesys** [comment] 2015-07-24 20:06
@gtfierro, you sure this aint a bug in your remote actuation code? Do these phones have that code in them?

**Comment by gtfierro** [comment] 2015-07-24 20:08
They will all have it, yes. I'll take a look at it when I'm not brain-fried, but  can't I think off the top of my head of what the logic error could possibly be.

**Comment by j6kim** [comment] 2015-07-27 16:46
F01A is also having the same issue: the bottom fan randomly starts on its own. Jessica (the user) came in this morning. The phone was connected to Airbears 2. The app was trying to connect to the chair. Once the chair connection was established, the bottom fan was off initially. Then it randomly started on its own even when she turned it off.

**Comment by samkumar** [comment] 2015-07-28 02:25
@gtfierro, I noticed this commit on the Chair App: eac11b2760a756e3458310b5170cf90bc7dccb6f
Can you please clarify what you're doing here? In particular, is there any server-side code that accompanies it?

It seems like you're trying to support remote actuation of the chair. However, to the best of my knowledge, remote actuation was working via the phone and 15.4 before you added that code. I'm not sure what the consequences of having two actuation routes are, I definitely want to take a look at that.

Meanwhile, I'm going to edit the server code to write to a file whenever it initiates remote actuation (at least through the route that I created). That will make it clear where the source of the issue is.

**Comment by samkumar** [comment] 2015-07-28 02:29
@j6kim Can you please answer a few questions about how the fans turn on:
1. Do the fans turn on consistently after the phone connects to the chair, for the affected chairs? Or is it a "one-off" event?
2. When it happens, do the fans on the chair turn on first, and then the app updates a bit later? Or is there no perceptible difference between the app showing the fans on and the fans actually turning on?

**Comment by samkumar** [comment] 2015-07-28 02:48
I've edited the server side code. If anyone visits site for remote actuation and tries it out, please let me know so I don't mistakenly assume that that's the server-side code erroneously sending an actuation message.

**Comment by j6kim** [comment] 2015-07-28 05:16
@samkumar99 
1) the fans consistently turned on after the phone was connected to the chair. It wasn't a one-time incident. It happened several times over an hour.
2) when the users noticed the fan being on, they checked the phone app - the sliding scale on the phone was already moved to the cooling side. They thought the chair & app settings changed at the same time.

**Comment by gtfierro** [comment] 2015-07-28 05:42
Sam, we added that route to support actuation specifically because remote actuation was _not_ working and we needed a hack to finish the paper. There is no border router near the chairs, so it is impossible that anyone is sending an actuation command via the site.

The way my hack works is by polling a special sMAP stream that must be formatted in a certain way, so unless someone is publishing a very uniquely formed message, it shouldn't be that path of actuation. None of the new actuation code in the phone touches your actuation code -- it is all done out of band to the PECS server stuff. A better solution would be to completely remove and stop the server side actuation code from the PECS repository as well as the hack actuation. There's absolutely no need for remote actuation on the chairs anymore.

**Comment by samkumar** [comment] 2015-07-28 06:05
Removing the code for remote actuation may be a temporary solution. It's probably the safest solution for CBE's deployment.

But we should definitely talk about why the code wasn't working for you. The remote actuation code that I wrote should work over both 15.4 as well as the phone. I have demoed the code many times (even to you, at the IoT final presentations in May). I tested it right now and it works fine.

The server-side code is a bit complicated if you haven't written it, partially because it has attached a lot of baggage from previous features/code that have since been removed (like the firestorm proxy) so I might rewrite it more clearly sometime soon.

But in general, the way remote actuation works (as I implemented it) is that the server side code stores in memory a dictionary containing the "current settings" of the chair. The phone sends a POST request to update this dictionary whenever the user changes the settings, or whenever the chair sends its current state over bluetooth (which it does periodically, in order to support the screen interface should that be added). Remote actuation updates this dictionary server-side. The phone periodically polls the dictionary and updates the chair when necessary. The server stores as "last modified" time so the phone knows whether it's sufficiently recent to do this.

So conceptually it's not too complicated. I think that if I rewrote the server-side code I could make it much cleaner. It's probably worth doing that sometime soon.

**Comment by gtfierro** [comment] 2015-07-28 06:06
Yes, this is probably the problem.

**Comment by samkumar** [comment] 2015-07-28 06:10
I'll try to rewrite the server-side code more cleanly sometime this week. I'll definitely get to it this weekend.

Do you think I should try consolidating everything into a single sMAP driver? What I mean is to have a single sMAP driver that dynamically adds streams as chairs are discovered. Or should I keep it as it currently is, where there is a sMAP driver for every chair, and a central gateway that all communcations pass through?

**Comment by gtfierro** [comment] 2015-07-28 06:12
No, we need to rethink the way the whole thing is done. Don't worry about rewriting the server-side stuff this week. @immesys you and I and Sam should have a discussion soon.

**Comment by j6kim** [comment] 2015-07-28 21:49
@gtfierro & @immesys 
I was planning to deploy the chairs on Aug 10th. Would rewriting the softwre affect the depoyment schedule?

**Comment by samkumar** [comment] 2015-07-28 23:58
In my opinion rewriting the code is more of a long-term thing, since the issues have to do with maintainability, not functionality. The current code will probably be fine for the deployment. Michael and Gabe, do you agree?

**Comment by j6kim** [comment] 2015-07-29 14:03
@samkumar99
Do we know what causes the bottom fan starting randomly on its own?

**Comment by gtfierro** [comment] 2015-07-29 14:17
I've just about ruled out that it's my actuation path. I deleted the timeseries on the server just in case, so the phones should just error out on fetching the actuation request and not even touch the actual logic. I can't do this from my laptop, but removing [this line](https://github.com/SoftwareDefinedBuildings/PECS-Android-App/blob/master/ChairTalk/app/src/main/java/com/michaelchen/chairtalk/MainActivity.java#L355) should remove beyond any doubt the polling actuation loop as the culprit. 

@samkumar99 I tried stopping the chair actuation server on shell, but it seems like stopping that server prevents chairs from reporting readings. So, I commented out [these lines](https://github.com/SoftwareDefinedBuildings/PECS-chair/blob/master/app/PECS-chair/server/actuateServer.py#L101-L122), because that seems to be where the actuation was handled.

@j6kim let us know if any more chairs have accidental actuations.

**Comment by samkumar** [comment] 2015-07-29 15:46
@gtfierro Yes, I believe that commenting out that code should stop my path for remote actuation.

@j6kim Not yet. I believe the issue is either in the app or the server code; if it were in the chair code, then there would be a delay before the phone updates. Hopefully Gabe's experiment will confirm that the issue is in the remote actuation path.

I was also wondering, when the fan turns on, is it always the bottom fan? And does it turn on all the way or only part of the way?

**Comment by j6kim** [comment] 2015-07-29 16:09
@samkumar99 @gtfierro 
so far, the issue only applies to the bottom fan.  if this happens again, i'll let you know.

**Comment by gtfierro** [comment] 2015-07-29 18:20
This issue might start up again. Here's my theory: [these lines](https://github.com/SoftwareDefinedBuildings/PECS-chair/blob/master/app/PECS-chair/server/actuateServer.py#L101-L122) if uncommented, cause the spurious actuation issue. If commented out, it causes the phone crash.

**Comment by j6kim** [comment] 2015-07-29 18:28
I asked Therese, Jessica, & Caroline to report to me if the issues with the bottom fan occur again. So far no issues reported this morning. I'll let you know if the fan randomly starts again.

**Comment by samkumar** [comment] 2015-07-29 19:56
I think I know why commenting out that code makes the phone crash. You need to keep the statement timestamp = float(res.text). The variable timestamp needs to be set before returning.

I took a closer look at the code just now. The code you commented out is the code for 15.4 actuation, not phone actuation (sorry, I should have told you this earlier but I also didn't realize at the time).

To stop the phone actuation path that I had built in, you'll need to comment out the GET handler. Specifically the part where it makes the get request to the smap driver http server for that chair and returns what it gets back.

**Comment by gtfierro** [comment] 2015-07-29 21:31
Tell me exactly what needs to be commented out by referencing lines on the Github source. In the meantime, I killed the chairForwarder process, which seems to have fixed everything.

**Comment by samkumar** [comment] 2015-07-29 22:25
I'm on a phone replying via email, so referencing GitHub lines is difficult. Replacing "if 'macaddr' in qs" with "if False" should disable my actuation path.

chairForwarder responds to messages received via 15.4. What was fixed by killing it?

**Comment by yongchaozhai** [comment] 2015-07-31 19:22
Chair 'f00f.
Same issue. Bottom fan turned on automatically around 12:20pm.

.

**Comment by gtfierro** [comment] 2015-08-04 07:33
I've performed the change mentioned by @samkumar99 , so hopefully we won't see this issue now.

**Comment by gtfierro** [comment] 2015-08-11 21:59
Have any fans spontaneously turned on over the past week?

**Comment by j6kim** [comment] 2015-08-11 22:11
No one reported any issues about bottom fan randomly starting. But, I found something strange with my chair fans (f014). Yesterday (8/10) I left the office before noon and came back this morning (8/11). On Sam's plotter, both the bottom & back fans appear to have run overnight. Could this be related to this issue?

**Comment by gtfierro** [comment] 2015-08-11 22:13
It will report them as on even though no one is sitting in the chair. To get the correct value, just multiply by occupancy (1 or 0). You have to manually set the chair to "off" from the app to see the 0-values on the  plotter

**Comment by gtfierro** [comment] 2015-08-11 22:13
Marking this as closed because the issue has not presented itself since I made the change suggested by @samkumar99

**Closed as completed by gtfierro** 2015-08-11 22:13 UTC
Labels: App Issue
