### ISSUE TITLE
Status message on screen is unhelpful

### ISSUE THREAD

**Issue by immesys** [SoftwareDefinedBuildings/PECS-chair#1] opened 2015-07-10 23:13 UTC
It leads me to believe that chair is not work but chair is work

**Comment by gtfierro** [comment] 2015-07-10 23:45
Issue fixed in https://github.com/SoftwareDefinedBuildings/PECS-Android-App/commit/375c0c9351a75d25e70d41f460576b32758c5065, new binaries for apps added in ef9da7f093866e5f7418c62fe5c4c78d41eb4c64

**Closed as completed by gtfierro** 2015-07-10 23:45 UTC

**Comment by samkumar** [comment] 2015-07-11 01:00
Can you please elaborate more on what the issue is? I'm fairly confident
that changing that XOR to an AND will break things.

**Comment by gtfierro** [comment] 2015-07-11 01:35
The issue is that the phone app gets stuck on "waiting for chair" in the status, despite it being connected to both the phone and to sMAP.

I looked at the app, and both XOR conditions were true when the app started, so the status was never changed to "connected to chair". I haven't experienced a single issue with changing to AND.

What will break?

**Comment by gtfierro** [comment] 2015-07-11 01:42
I made this change, which seems to capture what I think you were doing

https://github.com/SoftwareDefinedBuildings/PECS-Android-App/commit/9c3096d0615ad4937ce9151b01282483990a9e7f

I correctly get the status updates now

**Comment by samkumar** [comment] 2015-07-11 02:36
Yes, now the code looks right. The XOR was an optimization I added to avoid
some work if the "connected" status didn't change. However, looking at it
again, you're correct that on initialization I still need to do that work.
We could add an additional condition (something like "if (firstTime ||
(connected ^ verifiedConnection)) ..."), but simply removing the condition,
like you did, is cleaner and still correct. I don't think we need to make
any more changes after the last change you made. Thanks Gabe.

**Comment by immesys** [comment] 2015-07-11 02:52
You should not use xor with booleans. Use !=. Xor is for bitwise operations.
